name: Build the code

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:

    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: | 
        set -x
        sudo apt install -y linux-headers-$(uname -r)

    - name: Run "make"
      run: make
